name: Build APK
description: Builds an installable APK for android users

inputs:
  filename:
    description: The filename to create
    required: true
  type:
    default: release
    description: debug or release

runs:
  using: composite
  steps:
    - shell: bash
      run: | # shell
        flutter build apk --${{ inputs.type }}
        mv build/app/outputs/flutter-apk/app-${{ inputs.type }}.apk "${{ inputs.filename }}"
