on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        test:
          - os: ubuntu-latest
            name: 🐧
          - os: macos-latest
            name: 🍎
          - os: windows-latest
            name: 🏁
    name: ${{ matrix.test.name }}
    runs-on: ${{ matrix.test.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install
      - uses: ./.github/actions/test
